### ISSUE TITLE
v2.1.0 causes "Cannot find module" error

### ISSUE THREAD

**Issue by wub** [jeanverster/chakra-ui-steps#134]
After updating from 2.0.4 to 2.1.0, I now get this error (using this with Remix - so the code is running on both server and client).

```
[server] Error: Cannot find module '/Users/x/x/client/node_modules/chakra-ui-steps/dist/chakra-ui-steps.umd.cjs'
[server]     at createEsmNotFoundErr (node:internal/modules/cjs/loader:1112:15)
[server]     at finalizeEsmResolution (node:internal/modules/cjs/loader:1105:15)
[server]     at resolveExports (node:internal/modules/cjs/loader:579:14)
[server]     at Function.Module._findPath (node:internal/modules/cjs/loader:648:31)
[server]     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1076:27)
[server]     at Function.Module._load (node:internal/modules/cjs/loader:934:27)
[server]     at Module.require (node:internal/modules/cjs/loader:1157:19)
[server]     at require (node:internal/modules/helpers:119:18)
[server]     at Object.<anonymous> (/Users/x/x/client/app/root.tsx:5:37)
[server]     at Module._compile (node:internal/modules/cjs/loader:1275:14)
[server] yarn run dev:server exited with code 1
[remix] The path "chakra-ui-steps" is imported in app/root.tsx but "chakra-ui-steps" was not found in your node_modules. Did you forget to install it?
```

I imagine it might have something to do with this change? 

2.0.4:
```json
  "main": "./dist/chakra-ui-steps.umd.js",
  "module": "./dist/chakra-ui-steps.es.js",
  "exports": {
    ".": {
      "import": "./dist/chakra-ui-steps.es.js",
      "require": "./dist/chakra-ui-steps.umd.js"
    }
  },
```

2.1.0:
```json
  "main": "./dist/chakra-ui-steps.umd.cjs",
  "module": "./dist/chakra-ui-steps.mjs",
  "exports": {
    ".": {
      "import": "./dist/chakra-ui-steps.mjs",
      "require": "./dist/chakra-ui-steps.umd.cjs"
    }
  },
```

**Comment by arslansajid** [comment]
I was using the version `2.0.4` and after upgrading to `2.1.0` facing the same problem.

**Comment by alisamar** [comment]
After upgrading to 2.1.0, I have the same problem with the Jest test.

https://github.com/jeanverster/chakra-ui-steps/issues/134#issuecomment-1725255696 this worked for me too.

 FAIL  src/component/index.spec.tsx
  ● Test suite failed to run

    Cannot find module 'chakra-ui-steps' from 'src/theme/index.ts'

    Require stack:
      src/theme/index.ts
      test/index.tsx
      src/component/index.spec.tsx

**Comment by 60pfennig** [comment]
This is still a problem! All versions >2.0.4  are not usable with NextJs 14.2.3
